stages:
    - dev_deploy
    - master_deploy
cache:
    paths:
     - node_modules/
# job1:
#     stage: dev_deploy
#     except:
#         - master
#     tags:
#         - lottery_dev_tag
#     script:
#         - yarn install
#         - yarn run build
#         - cd /data/choujiang
#         - if [ -d "lottery_front" ] ; then 
#         - sudo rm -rf lottery_front
#         - fi
#         - sudo cp -rf /home/gitlab-runner/builds/f72b38c0/0/mobile/easy_front /data/choujiang
job2:
    stage: master_deploy
    only:
        - master
    # when: manual
    tags:
        - easy_front_tag
    script:
    script:
        - yarn install
        - yarn run build
        - cd /data/choujiang
        - if [ -d "lottery_front" ] ; then 
        - sudo rm -rf lottery_front
        - fi
        - sudo cp -rf /home/gitlab-runner/builds/48368a1b/0/mobile/easy_front /data/choujiang
        - sudo rsync -azhe ssh /data/choujiang/easy_front/dist/ choujiang:/data/choujiang/
