export default {
  login: '/api/login',
  logout: '/user/logout',
  userInfo: '/user/info',
  remain: '/user/remainTime',
  awardsAdd: '/award/awardsAdd',
  awardList: '/award/awardList',
  isLotteryOver: '/award/isLotteryOver',
  getLucyNum: '/award/getLucyNum',
  updateAwardInfo: '/award/updateAwardInfo',
  joinAward: '/award/joinAward',
  awardItem: '/award/getAwardItem',
  updateUserInfo: '/user/updateUserInfo',
  uploadAvatar: '/user/uploadAvatar',
  getAllUser: '/user/getAllUser',
  uploadFashionImg: '/user/uploadFashionImg',
  fashionImgAdd: '/user/fashionImgAdd',
  getFashionGradeList: '/user/getFashionGradeList',
  getFashionImgList: '/user/getFashionImgList',
  getPerformList: '/user/getPerformList',
  commitFashionComment: '/user/commitFashionComment',
  commitPerformComment: '/user/commitPerformComment',
  addDanmu: '/user/addDanmu',
  changeDanmuStatus: '/user/changeDanmuStatus',
  getDanmuList: '/user/getDanmuList',
  changeCommentStatus: './user/changeCommentStatus',
  getCommentStatus: '/user/getCommentStatus'
}
